### ISSUE TITLE
[nice to have] avoid using trailing comma directly after the shared link

### ISSUE THREAD

**Issue by PrettyWood** [samuelcolvin/smokeshow#16]
Hey Samuel I just had a look on the pydantic PR. Looks simple to setup and use! Well done!
I just noticed that in Github actions the generated message is
```console
Site created with root smokeshow.helpmanual.io/2u3e441k2v375b2t1r0v/, uploading 63 files...
```
When you click on the link it hence goes to `smokeshow.helpmanual.io/xyz/,` with the trailing comma, which is annoying.
Maybe a trailing dot would be better as it's automatically removed by the browser?

Ref: https://github.com/samuelcolvin/smokeshow/blob/2985a676ff057394e032a4713c5d8c572bb40744/cli/smokeshow/main.py#L113

EDIT: just saw that there is at the end
```console
upload complete ✓ site size 2.9MB
go to smokeshow.helpmanual.io/xyz
```
but could still be nice to have the working link at the beginning as well

**Comment by samuelcolvin** [comment]
Thanks, I'll fix. I put the link at the bottom of the output for that reason, but I agree removing it from the first line would be good too.
